### PR TITLE
Feature/laravel6 compat

### PR DESCRIPTION
**Pull request by peerrabe**
tested with a blank laravel 6 installation...

### CODE REVIEW

**Comment by peerrabe** [comment]
how do we handle this styleci issue? i don't see any need to bring all => to same position?

**Comment by peerrabe** [comment]
~~latest commit "fixes" an issue with running `yarn prod`. the command gives errors with bootstrap 4.4, maybe you find a better way to handle that~~.

**Comment by peerrabe** [comment]
latest commit is dedicated to https://github.com/twbs/bootstrap/issues/29743 and not a laravel-tabler or a laravel problem. so i will revert this commit...

**Comment by cesaramirez** [comment]
This will be merged tomorrow

**Pull request merged**
